name: jess_mart
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

#-----------PACKAGES----------#
dependencies:
  flutter:
    sdk: flutter

#UTILITY PACKAGES
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.5.0
  url_launcher: ^6.1.3

  #ICONS
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

#state management
get: ^4.6.5
get_storage: ^2.1.1



#-------------- ./PACKAGES END--------------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  #---------------LOCAL ASSETS--------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/